name: travel_planner
description: A Travel Planner app using Flutter with Riverpod, GoRouter, Hive, and more.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  lottie: ^2.7.0
  google_maps_flutter: ^2.5.0
  intl: ^0.18.1
  uuid: ^4.2.1
  flutter_local_notifications: ^17.0.0
  image_picker: ^1.1.0
  flutter_image_compress: ^2.1.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9

  google_fonts: ^6.1.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  path_provider: ^2.1.3
  timezone: ^0.9.2 # Add this
  share_plus: ^7.2.2
  file_picker: ^6.2.0
  flutter_staggered_animations: ^1.1.1
  smooth_page_indicator: ^1.1.0
  shimmer: ^3.0.0
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/icons/
    - assets/images/
