name: travel_planner
description: A Travel Planner app using Flutter with Riverpod, GoRouter, Hive, and more.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core State Management & Navigation
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.1

  # Local Storage & Persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3

  # UI & Assets
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  fl_chart: ^0.66.0

  # Native Features & Integrations
  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  location: ^5.0.3
  flutter_polyline_points: ^2.0.0
  sqflite: ^2.3.2
  path_provider: ^2.1.3
  timezone: ^0.9.2
  flutter_timezone: ^1.0.8
  image_picker: ^1.2.0
  flutter_image_compress: ^2.4.0
  flutter_local_notifications: ^17.0.0
  share_plus: ^7.2.2
  file_picker: ^6.2.0
  http: ^1.5.0
  package_info_plus: ^8.0.0 # <-- THIS IS THE FIX (Upgraded from 5.0.1)
  flutter_native_splash: ^2.4.0 # <-- Re-added from previous step

  # Analytics & Monitoring
  firebase_core: ^2.25.0
  firebase_performance: ^0.9.3
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9

  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  badges: ^3.1.2
  dio: ^5.4.0  # Added for booking API integration

  # Virtual Assistant
  speech_to_text: ^7.3.0
  flutter_tts: ^3.8.5
  rxdart: ^0.27.7
  connectivity_plus: ^5.0.2
  mime: ^1.0.5

  # Export functionality
  csv: ^5.1.1
  pdf: ^3.10.7

  # OCR functionality
  google_ml_kit: ^0.16.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/icons/
    - assets/images/
    - assets/splash/ # <-- Re-added from previous step

# This entire section was missing from your file but is required for the splash screen
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash/logo.png
  android_12:
    image: assets/splash/logo.png
    icon_background_color: "#FFFFFF"
  fullscreen: true